name: Linear Chain
description: Linear qubit chain topology
grid_size: 16
num_qubits: 16
mux:
  enabled: false
qubits:
  0:
    row: 0
    col: 0
  1:
    row: 0
    col: 1
  2:
    row: 0
    col: 2
  3:
    row: 0
    col: 3
  4:
    row: 0
    col: 4
  5:
    row: 0
    col: 5
  6:
    row: 0
    col: 6
  7:
    row: 0
    col: 7
  8:
    row: 0
    col: 8
  9:
    row: 0
    col: 9
  10:
    row: 0
    col: 10
  11:
    row: 0
    col: 11
  12:
    row: 0
    col: 12
  13:
    row: 0
    col: 13
  14:
    row: 0
    col: 14
  15:
    row: 0
    col: 15
couplings:
- [0, 1]
- [1, 2]
- [2, 3]
- [3, 4]
- [4, 5]
- [5, 6]
- [6, 7]
- [7, 8]
- [8, 9]
- [9, 10]
- [10, 11]
- [11, 12]
- [12, 13]
- [13, 14]
- [14, 15]
visualization:
  show_mux_boundaries: false
  region_size: 16
id: linear-16
