name: Square Lattice with MUX
description: Square lattice topology with 2x2 MUX groups
grid_size: 8
num_qubits: 64
mux:
  enabled: true
  size: 2
qubits:
  0:
    row: 0
    col: 0
  1:
    row: 0
    col: 1
  2:
    row: 1
    col: 0
  3:
    row: 1
    col: 1
  4:
    row: 0
    col: 2
  5:
    row: 0
    col: 3
  6:
    row: 1
    col: 2
  7:
    row: 1
    col: 3
  8:
    row: 0
    col: 4
  9:
    row: 0
    col: 5
  10:
    row: 1
    col: 4
  11:
    row: 1
    col: 5
  12:
    row: 0
    col: 6
  13:
    row: 0
    col: 7
  14:
    row: 1
    col: 6
  15:
    row: 1
    col: 7
  16:
    row: 2
    col: 0
  17:
    row: 2
    col: 1
  18:
    row: 3
    col: 0
  19:
    row: 3
    col: 1
  20:
    row: 2
    col: 2
  21:
    row: 2
    col: 3
  22:
    row: 3
    col: 2
  23:
    row: 3
    col: 3
  24:
    row: 2
    col: 4
  25:
    row: 2
    col: 5
  26:
    row: 3
    col: 4
  27:
    row: 3
    col: 5
  28:
    row: 2
    col: 6
  29:
    row: 2
    col: 7
  30:
    row: 3
    col: 6
  31:
    row: 3
    col: 7
  32:
    row: 4
    col: 0
  33:
    row: 4
    col: 1
  34:
    row: 5
    col: 0
  35:
    row: 5
    col: 1
  36:
    row: 4
    col: 2
  37:
    row: 4
    col: 3
  38:
    row: 5
    col: 2
  39:
    row: 5
    col: 3
  40:
    row: 4
    col: 4
  41:
    row: 4
    col: 5
  42:
    row: 5
    col: 4
  43:
    row: 5
    col: 5
  44:
    row: 4
    col: 6
  45:
    row: 4
    col: 7
  46:
    row: 5
    col: 6
  47:
    row: 5
    col: 7
  48:
    row: 6
    col: 0
  49:
    row: 6
    col: 1
  50:
    row: 7
    col: 0
  51:
    row: 7
    col: 1
  52:
    row: 6
    col: 2
  53:
    row: 6
    col: 3
  54:
    row: 7
    col: 2
  55:
    row: 7
    col: 3
  56:
    row: 6
    col: 4
  57:
    row: 6
    col: 5
  58:
    row: 7
    col: 4
  59:
    row: 7
    col: 5
  60:
    row: 6
    col: 6
  61:
    row: 6
    col: 7
  62:
    row: 7
    col: 6
  63:
    row: 7
    col: 7
couplings:
- [0, 1]
- [0, 2]
- [1, 4]
- [1, 3]
- [2, 3]
- [2, 16]
- [3, 6]
- [3, 17]
- [4, 5]
- [4, 6]
- [5, 8]
- [5, 7]
- [6, 7]
- [6, 20]
- [7, 10]
- [7, 21]
- [8, 9]
- [8, 10]
- [9, 12]
- [9, 11]
- [10, 11]
- [10, 24]
- [11, 14]
- [11, 25]
- [12, 13]
- [12, 14]
- [13, 15]
- [14, 15]
- [14, 28]
- [15, 29]
- [16, 17]
- [16, 18]
- [17, 20]
- [17, 19]
- [18, 19]
- [18, 32]
- [19, 22]
- [19, 33]
- [20, 21]
- [20, 22]
- [21, 24]
- [21, 23]
- [22, 23]
- [22, 36]
- [23, 26]
- [23, 37]
- [24, 25]
- [24, 26]
- [25, 28]
- [25, 27]
- [26, 27]
- [26, 40]
- [27, 30]
- [27, 41]
- [28, 29]
- [28, 30]
- [29, 31]
- [30, 31]
- [30, 44]
- [31, 45]
- [32, 33]
- [32, 34]
- [33, 36]
- [33, 35]
- [34, 35]
- [34, 48]
- [35, 38]
- [35, 49]
- [36, 37]
- [36, 38]
- [37, 40]
- [37, 39]
- [38, 39]
- [38, 52]
- [39, 42]
- [39, 53]
- [40, 41]
- [40, 42]
- [41, 44]
- [41, 43]
- [42, 43]
- [42, 56]
- [43, 46]
- [43, 57]
- [44, 45]
- [44, 46]
- [45, 47]
- [46, 47]
- [46, 60]
- [47, 61]
- [48, 49]
- [48, 50]
- [49, 52]
- [49, 51]
- [50, 51]
- [51, 54]
- [52, 53]
- [52, 54]
- [53, 56]
- [53, 55]
- [54, 55]
- [55, 58]
- [56, 57]
- [56, 58]
- [57, 60]
- [57, 59]
- [58, 59]
- [59, 62]
- [60, 61]
- [60, 62]
- [61, 63]
- [62, 63]
visualization:
  show_mux_boundaries: true
  region_size: 4
id: square-lattice-mux-64
