name: Square Lattice with MUX
description: Square lattice topology with 2x2 MUX groups
grid_size: 12
num_qubits: 144
mux:
  enabled: true
  size: 2
qubits:
  0:
    row: 0
    col: 0
  1:
    row: 0
    col: 1
  2:
    row: 1
    col: 0
  3:
    row: 1
    col: 1
  4:
    row: 0
    col: 2
  5:
    row: 0
    col: 3
  6:
    row: 1
    col: 2
  7:
    row: 1
    col: 3
  8:
    row: 0
    col: 4
  9:
    row: 0
    col: 5
  10:
    row: 1
    col: 4
  11:
    row: 1
    col: 5
  12:
    row: 0
    col: 6
  13:
    row: 0
    col: 7
  14:
    row: 1
    col: 6
  15:
    row: 1
    col: 7
  16:
    row: 0
    col: 8
  17:
    row: 0
    col: 9
  18:
    row: 1
    col: 8
  19:
    row: 1
    col: 9
  20:
    row: 0
    col: 10
  21:
    row: 0
    col: 11
  22:
    row: 1
    col: 10
  23:
    row: 1
    col: 11
  24:
    row: 2
    col: 0
  25:
    row: 2
    col: 1
  26:
    row: 3
    col: 0
  27:
    row: 3
    col: 1
  28:
    row: 2
    col: 2
  29:
    row: 2
    col: 3
  30:
    row: 3
    col: 2
  31:
    row: 3
    col: 3
  32:
    row: 2
    col: 4
  33:
    row: 2
    col: 5
  34:
    row: 3
    col: 4
  35:
    row: 3
    col: 5
  36:
    row: 2
    col: 6
  37:
    row: 2
    col: 7
  38:
    row: 3
    col: 6
  39:
    row: 3
    col: 7
  40:
    row: 2
    col: 8
  41:
    row: 2
    col: 9
  42:
    row: 3
    col: 8
  43:
    row: 3
    col: 9
  44:
    row: 2
    col: 10
  45:
    row: 2
    col: 11
  46:
    row: 3
    col: 10
  47:
    row: 3
    col: 11
  48:
    row: 4
    col: 0
  49:
    row: 4
    col: 1
  50:
    row: 5
    col: 0
  51:
    row: 5
    col: 1
  52:
    row: 4
    col: 2
  53:
    row: 4
    col: 3
  54:
    row: 5
    col: 2
  55:
    row: 5
    col: 3
  56:
    row: 4
    col: 4
  57:
    row: 4
    col: 5
  58:
    row: 5
    col: 4
  59:
    row: 5
    col: 5
  60:
    row: 4
    col: 6
  61:
    row: 4
    col: 7
  62:
    row: 5
    col: 6
  63:
    row: 5
    col: 7
  64:
    row: 4
    col: 8
  65:
    row: 4
    col: 9
  66:
    row: 5
    col: 8
  67:
    row: 5
    col: 9
  68:
    row: 4
    col: 10
  69:
    row: 4
    col: 11
  70:
    row: 5
    col: 10
  71:
    row: 5
    col: 11
  72:
    row: 6
    col: 0
  73:
    row: 6
    col: 1
  74:
    row: 7
    col: 0
  75:
    row: 7
    col: 1
  76:
    row: 6
    col: 2
  77:
    row: 6
    col: 3
  78:
    row: 7
    col: 2
  79:
    row: 7
    col: 3
  80:
    row: 6
    col: 4
  81:
    row: 6
    col: 5
  82:
    row: 7
    col: 4
  83:
    row: 7
    col: 5
  84:
    row: 6
    col: 6
  85:
    row: 6
    col: 7
  86:
    row: 7
    col: 6
  87:
    row: 7
    col: 7
  88:
    row: 6
    col: 8
  89:
    row: 6
    col: 9
  90:
    row: 7
    col: 8
  91:
    row: 7
    col: 9
  92:
    row: 6
    col: 10
  93:
    row: 6
    col: 11
  94:
    row: 7
    col: 10
  95:
    row: 7
    col: 11
  96:
    row: 8
    col: 0
  97:
    row: 8
    col: 1
  98:
    row: 9
    col: 0
  99:
    row: 9
    col: 1
  100:
    row: 8
    col: 2
  101:
    row: 8
    col: 3
  102:
    row: 9
    col: 2
  103:
    row: 9
    col: 3
  104:
    row: 8
    col: 4
  105:
    row: 8
    col: 5
  106:
    row: 9
    col: 4
  107:
    row: 9
    col: 5
  108:
    row: 8
    col: 6
  109:
    row: 8
    col: 7
  110:
    row: 9
    col: 6
  111:
    row: 9
    col: 7
  112:
    row: 8
    col: 8
  113:
    row: 8
    col: 9
  114:
    row: 9
    col: 8
  115:
    row: 9
    col: 9
  116:
    row: 8
    col: 10
  117:
    row: 8
    col: 11
  118:
    row: 9
    col: 10
  119:
    row: 9
    col: 11
  120:
    row: 10
    col: 0
  121:
    row: 10
    col: 1
  122:
    row: 11
    col: 0
  123:
    row: 11
    col: 1
  124:
    row: 10
    col: 2
  125:
    row: 10
    col: 3
  126:
    row: 11
    col: 2
  127:
    row: 11
    col: 3
  128:
    row: 10
    col: 4
  129:
    row: 10
    col: 5
  130:
    row: 11
    col: 4
  131:
    row: 11
    col: 5
  132:
    row: 10
    col: 6
  133:
    row: 10
    col: 7
  134:
    row: 11
    col: 6
  135:
    row: 11
    col: 7
  136:
    row: 10
    col: 8
  137:
    row: 10
    col: 9
  138:
    row: 11
    col: 8
  139:
    row: 11
    col: 9
  140:
    row: 10
    col: 10
  141:
    row: 10
    col: 11
  142:
    row: 11
    col: 10
  143:
    row: 11
    col: 11
couplings:
- [0, 1]
- [0, 2]
- [1, 4]
- [1, 3]
- [2, 3]
- [2, 24]
- [3, 6]
- [3, 25]
- [4, 5]
- [4, 6]
- [5, 8]
- [5, 7]
- [6, 7]
- [6, 28]
- [7, 10]
- [7, 29]
- [8, 9]
- [8, 10]
- [9, 12]
- [9, 11]
- [10, 11]
- [10, 32]
- [11, 14]
- [11, 33]
- [12, 13]
- [12, 14]
- [13, 16]
- [13, 15]
- [14, 15]
- [14, 36]
- [15, 18]
- [15, 37]
- [16, 17]
- [16, 18]
- [17, 20]
- [17, 19]
- [18, 19]
- [18, 40]
- [19, 22]
- [19, 41]
- [20, 21]
- [20, 22]
- [21, 23]
- [22, 23]
- [22, 44]
- [23, 45]
- [24, 25]
- [24, 26]
- [25, 28]
- [25, 27]
- [26, 27]
- [26, 48]
- [27, 30]
- [27, 49]
- [28, 29]
- [28, 30]
- [29, 32]
- [29, 31]
- [30, 31]
- [30, 52]
- [31, 34]
- [31, 53]
- [32, 33]
- [32, 34]
- [33, 36]
- [33, 35]
- [34, 35]
- [34, 56]
- [35, 38]
- [35, 57]
- [36, 37]
- [36, 38]
- [37, 40]
- [37, 39]
- [38, 39]
- [38, 60]
- [39, 42]
- [39, 61]
- [40, 41]
- [40, 42]
- [41, 44]
- [41, 43]
- [42, 43]
- [42, 64]
- [43, 46]
- [43, 65]
- [44, 45]
- [44, 46]
- [45, 47]
- [46, 47]
- [46, 68]
- [47, 69]
- [48, 49]
- [48, 50]
- [49, 52]
- [49, 51]
- [50, 51]
- [50, 72]
- [51, 54]
- [51, 73]
- [52, 53]
- [52, 54]
- [53, 56]
- [53, 55]
- [54, 55]
- [54, 76]
- [55, 58]
- [55, 77]
- [56, 57]
- [56, 58]
- [57, 60]
- [57, 59]
- [58, 59]
- [58, 80]
- [59, 62]
- [59, 81]
- [60, 61]
- [60, 62]
- [61, 64]
- [61, 63]
- [62, 63]
- [62, 84]
- [63, 66]
- [63, 85]
- [64, 65]
- [64, 66]
- [65, 68]
- [65, 67]
- [66, 67]
- [66, 88]
- [67, 70]
- [67, 89]
- [68, 69]
- [68, 70]
- [69, 71]
- [70, 71]
- [70, 92]
- [71, 93]
- [72, 73]
- [72, 74]
- [73, 76]
- [73, 75]
- [74, 75]
- [74, 96]
- [75, 78]
- [75, 97]
- [76, 77]
- [76, 78]
- [77, 80]
- [77, 79]
- [78, 79]
- [78, 100]
- [79, 82]
- [79, 101]
- [80, 81]
- [80, 82]
- [81, 84]
- [81, 83]
- [82, 83]
- [82, 104]
- [83, 86]
- [83, 105]
- [84, 85]
- [84, 86]
- [85, 88]
- [85, 87]
- [86, 87]
- [86, 108]
- [87, 90]
- [87, 109]
- [88, 89]
- [88, 90]
- [89, 92]
- [89, 91]
- [90, 91]
- [90, 112]
- [91, 94]
- [91, 113]
- [92, 93]
- [92, 94]
- [93, 95]
- [94, 95]
- [94, 116]
- [95, 117]
- [96, 97]
- [96, 98]
- [97, 100]
- [97, 99]
- [98, 99]
- [98, 120]
- [99, 102]
- [99, 121]
- [100, 101]
- [100, 102]
- [101, 104]
- [101, 103]
- [102, 103]
- [102, 124]
- [103, 106]
- [103, 125]
- [104, 105]
- [104, 106]
- [105, 108]
- [105, 107]
- [106, 107]
- [106, 128]
- [107, 110]
- [107, 129]
- [108, 109]
- [108, 110]
- [109, 112]
- [109, 111]
- [110, 111]
- [110, 132]
- [111, 114]
- [111, 133]
- [112, 113]
- [112, 114]
- [113, 116]
- [113, 115]
- [114, 115]
- [114, 136]
- [115, 118]
- [115, 137]
- [116, 117]
- [116, 118]
- [117, 119]
- [118, 119]
- [118, 140]
- [119, 141]
- [120, 121]
- [120, 122]
- [121, 124]
- [121, 123]
- [122, 123]
- [123, 126]
- [124, 125]
- [124, 126]
- [125, 128]
- [125, 127]
- [126, 127]
- [127, 130]
- [128, 129]
- [128, 130]
- [129, 132]
- [129, 131]
- [130, 131]
- [131, 134]
- [132, 133]
- [132, 134]
- [133, 136]
- [133, 135]
- [134, 135]
- [135, 138]
- [136, 137]
- [136, 138]
- [137, 140]
- [137, 139]
- [138, 139]
- [139, 142]
- [140, 141]
- [140, 142]
- [141, 143]
- [142, 143]
visualization:
  show_mux_boundaries: true
  region_size: 4
id: square-lattice-mux-144
